# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 19 Sep 2014 08:08:03 +0000
*               @ALL          0
*               @user         8
